## ----setup, include=FALSE------------------------------------------------
knitr::opts_chunk$set(echo = TRUE)

## ------------------------------------------------------------------------
library(dr4pl)
library(ggplot2)
library(drc)

## ------------------------------------------------------------------------
ggplot(drc_error_1, aes(x = Dose, y = Response)) +
  geom_point() +
  scale_x_log10() +
  ggtitle("drc_error_1")

## ------------------------------------------------------------------------
a <- tryCatch({
  drc::drm(Response~Dose, data = drc_error_1, fct = LL.4())
}, 
warning = function(war) {
  # warning handler picks up where error was generated
  print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})

## ------------------------------------------------------------------------
a <-tryCatch({
  dr4pl(Response~Dose, data = drc_error_1, method.robust = "Tukey")
},
warning = function(war) {
    # warning handler picks up where error was generated
    print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})
plot(a, text.title = "Error plot #1", indices.outlier = c(102))

## ------------------------------------------------------------------------
ggplot(drc_error_2, aes(x = Dose, y = Response)) +
  geom_point() +
  scale_x_log10() +
  ggtitle("drc_error_2")

## ------------------------------------------------------------------------
a <- tryCatch({
  drc::drm(Response~Dose, data = drc_error_2, fct = LL.4())
}, 
warning = function(war) {
  # warning handler picks up where error was generated
  print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})

## ------------------------------------------------------------------------
a <-tryCatch({
  dr4pl(Response~Dose, data = drc_error_2, method.init = "Mead", method.robust = "Huber" )
},
warning = function(war) {
    # warning handler picks up where error was generated
    print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})
b <- plot(a, breaks.x = c(0.00135, 0.0135, 0.135, 1.35, 13.5), text.title = "Error plot #2", indices.outlier = c(2,8) )
b

## ------------------------------------------------------------------------
ggplot(drc_error_3, aes(x = Dose, y = Response)) +
  geom_point() +
  scale_x_log10() +
  ggtitle("drc_error_3")

## ------------------------------------------------------------------------
a <- tryCatch({
  drc::drm(Response~Dose, data = drc_error_3, fct = LL.4())
}, 
warning = function(war) {
  # warning handler picks up where error was generated
  print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})


## ------------------------------------------------------------------------
a <-tryCatch({
  dr4pl(Response~Dose, data = drc_error_3, method.init = "Mead", method.robust = "absolute" )
},
warning = function(war) {
    # warning handler picks up where error was generated
    print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})
plot(a, indices.outlier = c(90, 101), text.title = "Error plot #3")

## ------------------------------------------------------------------------
ggplot(drc_error_4, aes(x = Dose, y = Response)) +
  geom_point() +
  scale_x_log10() +
  ggtitle("drc_error_4")

## ------------------------------------------------------------------------
a <- tryCatch({
  drc::drm(Response~Dose, data = drc_error_4, fct = LL.4())
}, 
warning = function(war) {
  # warning handler picks up where error was generated
  print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})

## ------------------------------------------------------------------------
a <-tryCatch({
  dr4pl(Response~Dose, data = drc_error_4, method.init = "Mead", method.robust = "absolute" )
},
warning = function(war) {
    # warning handler picks up where error was generated
    print(paste(war))
},
error = function(err) {
  # error handler picks up where error was generated
  print(paste(err))
})
plot(a, text.title = "Error plot #4", indices.outlier = c(1,100))

## ------------------------------------------------------------------------
a <- dr4pl(Response~Dose, data = sample_data_6)
plot(a, text.title = "Default Sample data #6")

## ------------------------------------------------------------------------
a <- dr4pl(Response~Dose, data = sample_data_6, method.init = "Mead")
plot(a, text.title = "Mead's Method")

## ------------------------------------------------------------------------
a <- dr4pl(Response~Dose, data = sample_data_6, method.init = "Mead", method.robust = "absolute")
plot(a, text.title = "Mead's method & absolute")

## ------------------------------------------------------------------------
a <- dr4pl(Response~Dose, data = sample_data_6, method.init = "Mead", method.robust = "Tukey")
plot(a, text.title = "Mead's method & Tukey's biweight")

## ------------------------------------------------------------------------
a <- dr4pl(Response~Dose, data = sample_data_3, method.init = "Mead")
b <- plot(a, text.title = "Sample data #3")
b

## ------------------------------------------------------------------------
b <- summary(a)
b$coefficients

## ------------------------------------------------------------------------
values <- IC(a, c(10, 30, 50, 70, 90))
values

